version: "2"
services:
  web:
    platform: linux/x86_64
    image: odoo:10.0
    links:
      - db
    ports:
      - "8069:8069"
    restart: always
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    platform: linux/x86_64
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
   
  admin:
    platform: linux/x86_64
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgresql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: postgres



volumes:
  odoo-web-data:
  odoo-db-data: